### PR TITLE
Add buildkit support for cross-platform docker image publishing

### PR DESCRIPTION
**Pull request by idcrook**
## Description

PR for implemention of #60 multi-arch docker image publishing

- Added rules to Makefile (and invoke in .travis.yml)

  1. launch a buildkitd

  2. build cross-platform docker container images (`amd64`, `arm64`, `armhf`) and tag

  3. Tag archs and latest. Create and push multi-arch image using `docker manifest`. Tags for the pushed images are set in the Makefile

- Created `Dockerfile.multi-arch`

  - works like standard project Dockerfile, but adds cross-platform support
     1. `go build` builds appropriate arch in build stage
     2. `alpine`-based image is created adding `ca-certificates` and the app user.

TODO

 - [X] Get signoff on docker image platform tag names (Mooted with 'latest' tag)
 - [X] annotate image manifests and support multi-arch image tags
 - [X] ~~replace Dockerfile with Dockerfile.multi-arch?~~

## How Has This Been Tested?

```bash
# run as root user on an Ubuntu 18.04 machine
make buildkitd
BUILDKIT_PUSH_TO_REPO=false make docker-buildkit-images
```

```shell
# run as root on an ubuntu VM
make buildkitd
DOCKER_HUB_REPO=dpcrook/inlets make docker-buildkit-images
DOCKER_HUB_REPO=dpcrook/inlets make docker-buildkit-push-manifests
```

With this PR, on each of the supported architectures, something like the following will work:

```shell
$ sudo docker run -i dpcrook/inlets:latest
$ uname -m
aarch64
```
Also works on each of support platform using simple image tag `:Version` (no `-{arch}` necessary)
```shell
$ docker run -i dpcrook/inlets:2.0.3-5-gf88adc4
$ uname -m
armv7l
```

## How are existing users impacted? What migration steps/scripts do we need?

This PR will affect the travis/release phase for docker images. 
 - Adds support for building cross-platform docker images, including on travis-ci.

## Checklist:

I have:

- [X] updated the documentation and/or roadmap (if required)
- [X] read the [CONTRIBUTION](https://github.com/alexellis/inlets/blob/master/CONTRIBUTING.md) guide
- [X] signed-off my commits with `git commit -s`
- [X] added unit tests (implicit in travis-ci builds and deploys)

### CODE REVIEW

**Comment by idcrook** [comment]
Just a disposition on travis-ci [Build \#141 error](https://travis-ci.org/alexellis/inlets/builds/530854554#L446): It "failed" to push the buildkit-built image since `docker-login` was unsuccessful. 

Cverall, it looks like it is working as intended 🍦

**Comment by idcrook** [comment]
I think I'm almost ready for review with latest commit

**Comment by alexellis** [comment]
Thank you. Are we able to retain the default way of building with `docker build` somewhere for local dev?

**Comment by idcrook** [comment]
The Makefile still supports, as it did before, docker builds.  That piece hasn’t been changed.

**Comment by alexellis** [comment]
Is there a way we can avoid buildkitd? I saw somewhere that Docker now ships with the ability to turn on buildkit for the build step?

@tonistiigi can you help with my question?

**Comment by idcrook** [comment]
This PR uses buildkitd all within Docker, including on travis. Not sure if that is what you are asking_

> Docker now ships with the ability to turn on buildkit for the build

> Is there a way we can avoid buildkitd? I saw somewhere that Docker now ships with the ability to turn on buildkit for the build step?
> 
> @tonistiigi can you help with my question?

**Comment by alexellis** [comment]
No, that's not what I mean.

I don't think we need to couple ourselves to buildkitd.

See this [documentation page](https://docs.docker.com/develop/develop-images/build_enhancements/#to-enable-buildkit-builds)

Alex

**Comment by idcrook** [comment]
> See this [documentation page](https://docs.docker.com/develop/develop-images/build_enhancements/#to-enable-buildkit-builds)

Thanks. I think this docker feature is relatively new. I'll take a look at the docs, as it at first glance looks similar in outline, and PR could be adapted to use this as replacement.

It could also probably be done for normal docker build in the Makefile, etc. to reduce code and task duplication.  As it's currently structured, there are duplicated Go-on-docker cross-builds for the various architectures in the full local and/or CI/CD flows.

**Comment by idcrook** [comment]
Starting research for buildkitd-less docker cross-platform builds. Noting here possibly related issues:
 - https://travis-ci.community/t/docker-builds-are-broken-if-buildkit-is-used-docker-buildkit-1/2994
 - https://github.com/moby/buildkit/issues/943

**Comment by alexellis** [comment]
Hi @idcrook I'd like to revisit this.

What do we need to do?

Alex

**Comment by idcrook** [comment]
I have not done anything tangible to change the way it uses buildkitd.

It was working then (including on travis-ci), and it is not coupled too heavily upon other elements of this project, although in its form there may be some code duplication.

I do not have time currently to refactor this or  change its methodology. If that is still what is wanted, perhaps another PR is called for. I'd be happy to hand this idea off to someone else.

**Comment by idcrook** [comment]
Obviated by #108

**Comment by idcrook** [comment]
Closing this PR and deleting its hosted repo

**Comment by alexellis** [comment]
Thank you for your help @idcrook 

I think we could use the approach from #108 in some of the other projects such as:

https://github.com/openfaas/nats-queue-worker/blob/master/Dockerfile

https://github.com/alexellis/minio-kv

https://github.com/alexellis/expressjs-k8s

https://github.com/alexellis/jaas

**Pull request closed without merging**
