### PR TITLE
adding the ASCII logo to the help messages and the version message

### PR DESCRIPTION
**Pull request by linuxjuggler**
Signed-off-by: Zaher Ghaibeh <z@zah.me>

## Description
This should get https://github.com/alexellis/inlets/issues/83 off.

## How Has This Been Tested?
I test it manually by executing the commands

Screen Shot 2019-08-19 at 12 47 04 PM

Screen Shot 2019-08-19 at 12 47 51 PM
Screen Shot 2019-08-19 at 12 48 09 PM

## Checklist:

I have:

- [x] updated the documentation and/or roadmap (if required)
- [x] read the [CONTRIBUTION](https://github.com/alexellis/inlets/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by alexellis** [comment]
It would be great if you could reformat your commit message to fit in with the contribution guide.

https://chris.beams.io/posts/git-commit/

Namely:

* Use the commit body to explain why there was a change and how it was tested
* Don't use more than 72 chars for the "title" of the commit message
* Start the commit with "Add" vs "adding" i.e. "Add ASCII logo"

You can update with this command:

```
git commit --s --amend
```

One small change I would like (faas-cli works like this):

- `faas-cli --help` -> print usage, no-logo
- `faas-cli` -> print logo and usage

If this isn't easy to achieve, then we can do it at a later date.

**Comment by linuxjuggler** [comment]
> Please don't repeat the ASCII text everywhere it's used.
> 
> Extract this to a const, just like the sample shared for faas-cli, then use `fmt.Sprintf()`
> 
> https://github.com/openfaas/faas-cli/blob/master/commands/version.go
> 
> Thanks

Each file uses this text once, so this might take a bit of time from me as I have modified three files, not one. I'll have to start reading about go inheritance so I can extract the small text into its own *class* (not sure yet what they call it in GO) and use it within those three files.

I have looked at the `version.go` file you referenced and I'll see how can I use the same thing in those 3 files.

**Comment by linuxjuggler** [comment]
I'll close it, for now, so if anyone else wants to pick up the same ticket and solve it. I'll create another PR later once I got everything as requested here and if the ticket is still open.

**Comment by alexellis** [comment]
Hi @linuxjuggler since I've already spend my own time reviewing this and giving feedback, can you please commit to finish the work?

If there is anything confusing, please feel free to ask, likewise you can copy the approach of the faas-cli or k3sup. https://github.com/alexellis/k3sup/pull/4

Alex

**Comment by alexellis** [comment]
> Each file uses this text once, so this might take a bit of time from me.

The code example I sent you at the beginning, which I suggested following uses something called a `const`, it's a variable which is available at the package level, similar to a global variable.

Please go back to the original issue https://github.com/alexellis/inlets/issues/83 and read the code that it's linking to.

**Comment by linuxjuggler** [comment]
Hey @alexellis thanks for the feedback, I'll check and see what can I do this weekend.

I appreciate your time and the feedback that you have given, but I also have works to do on my own to cover my expenses.

**Comment by alexellis** [comment]
This is literally a 5 min change. You reached out to me specifically asking for coaching and mentoring. That means me investing my time to help you, which is what I'm trying to do here. 

If you want to own the issue then just reopen the pull request, to show that you are committing to it.

**Comment by linuxjuggler** [comment]
Hey @alexellis Yes I have reached to you to help me learn the GO language, but at the same time you didn't ask me about my time, nor we spent any time planning how I should approach the language.

You provided me with a link to the resource that you have gathered for openfaas and gave me this ticket to work on.

I am grateful for your help, but you should also consider that not all of us is working full time on opensource projects, and we have other things to do most of the time.

I know you are busy person, and I can fully understand your point of view, but you should also see it from my own point of view too.

anyway, am working on a better approach based on your comment and I'll open a PR once I finish as I already deleted the old fork I used to have.

**Comment by alexellis** [comment]
Thanks

**Pull request closed without merging**
