### PR TITLE
Add AWS scripts to provision inlets exit nodes

### PR DESCRIPTION
**Pull request by mbacchi**
## Description
This adds two new scripts to provision AWS Lightsail
and AWS EC2 resources using Terraform.

Fixes: https://github.com/alexellis/inlets/issues/88

Signed-off-by: Matt Bacchi <mbacchi@gmail.com>

## How Has This Been Tested?
Using these two scripts I have brought up AWS Lightsail and EC2 instances as Inlets exit nodes and verified they work as expected.

## Checklist:

I have:

- [x] updated the documentation and/or roadmap (if required)
- [x] read the [CONTRIBUTION](https://github.com/alexellis/inlets/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @mbacchi 

Thank you for your interest in inlets and for spending time to automate and package it for AWS.

Unfortunately I cannot accept this PR because it is far too complex for me to maintain with my other commitments. Even if I merge it, other people will expect me to maintain it. I think you should maintain this in your own repo, and then send me a link to it, so that it can be listed prominently in the README for anyone who wants to use it.

I'd be happy to accept a simple script that matched the DigitalOcean approach, but which used `aws-cli` instead of terraform etc.

It would be great if you could do both, but I understand if you don't.

Alex

**Comment by mbacchi** [comment]
The reason for using Terraform is because the commands for configuring AWS EC2 are [quite lengthy](https://mbacchi.github.io/2019/08/21/inlets-aws-ec2.html#using-the-aws-cli).

I think I will be able to host this bash script in my repository, along with the terraform. I'll also write a simple shell script with AWS CLI commands for Lightsail, which is much more straightforward than EC2 for the Inlets repository in the hacks directory.

I'll work on this in the next couple weeks as time permits.

**Comment by alexellis** [comment]
Thank you @mbacchi 

I'm looking forward to hearing from you. Let me know if you can close this PR and raise a new one with your single-command lightsail and EC2 scripts.

I'd be very happy for you to host this PR content in your own repo and to link back to it.

**Comment by alexellis** [comment]
Please send the follow-up PR with the simple provisioning script, and the link back to your repo with these scripts when ready 👍

**Pull request closed without merging**
