### PR TITLE
WIP: Switch to using github.com/rancher/remotedialer for the transport

### PR DESCRIPTION
**Pull request by ibuildthecloud**
Fundamentally Inlets must perform tunneling and reverse proxying. Prior
to this commit both functions in Inlets are custom implementations tied
quite heavily to HTTP 1.1 request/response with no bi-directional
communication.

This patch replaces both tunneling and proxying with external libraries.
The transport layer is switched to using
github.com/rancher/remotedialer. Remote dialer allows tunneling
connections at a net.Conn level so higher level protocols such
as HTTP, HTTP2, WebSockets, gRPC, etc need not require specific
tunneling logic only proxy logic.

For proxying logic we use Kubernetes UpgradeAwareHandler which builds on
top of go's built in httputil.ReverseProxy but adds support for
"Connection: Upgrade" requests and HTTP response HTML rewriting. Once
Inlets switches to go 1.12 it might be possible to drop the Kubernetes
library and instead use the bare httputil.ReverseProxy as go 1.12 adds
support for proxying WebSockets.

### CODE REVIEW

**Comment by alexellis** [comment]
Derek remove label: invalid

**Comment by alexellis** [comment]
I tried this on my Linux machine and it looked to work as expected :smile: 

The issue I had was when running hey, it seemed to saturate available file-descriptors and then give non 2xx error codes with no debug information displayed.

```
# where 8000 is the exit node
hey -n 1000 -c 10 http://127.0.0.1:8000/
```

Increasing `ulimit -n` in the terminal session helped a lot, but raised some concerns for me. I'd like your take on it and I think the remotedialer solution looks :100: 

Alex

**Comment by alexellis** [comment]
@ibuildthecloud I think there's a potential bug in the client code now in how it connects to the remote side, here it always appends ws:// even if ws:// or wss:// was added by the user. Could you fix please?

```
alex@alexx:~/go/src/github.com/alexellis/inlets$ ./inlets client --remote wss://lon1-exit.example.com --token 7f3ecd23056735dc8ef471ac992a51cc4550fe4 --upstream http://192.168.0.26:31112
2019/04/05 09:04:08 Upstream:  => http://192.168.0.26:31112
map[Authorization:[Bearer 7f3ecd23056735dc8ef471ac992a51cc4550fe4] X-Inlets-Id:[e171b8cbb1124e84a254c3de5bb19cb8] X-Inlets-Upstream:[=http://192.168.0.26:31112]]
INFO[0000] Connecting to proxy                           url="ws://wss://lon1-exit.example.com/tunnel"
ERRO[0000] Failed to connect to proxy                    error="dial tcp: lookup wss on 127.0.1.1:53: no such host"
ERRO[0000] Failed to connect to proxy                    error="dial tcp: lookup wss on 127.0.1.1:53: no such host"
```

**Comment by ibuildthecloud** [comment]
I fixed the leak and will now check on the client side for ws:// in the remote address.

**Pull request merged**
