### PR TITLE
Add Windows distributions in Makefile

### LINKED ISSUE #23: Feature request: Publish a binary for Windows
## Expected Behaviour

Publish a binary for Windows.

## Current Behaviour

Untested and no binary available

## Possible Solution

Update the Makefile in the `dist` section

### PR DESCRIPTION
**Pull request by rleungx**
## Description
The PR adds one more distribution: `windows-amd64`. Closes #23.

## How Has This Been Tested?
Manually test on my Windows

## How are existing users impacted? What migration steps/scripts do we need?
No.

## Checklist:

I have:

- [x] updated the documentation and/or roadmap (if required)
- [x] read the [CONTRIBUTION](https://github.com/alexellis/inlets/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`

### CODE REVIEW

**Comment by alexellis** [comment]
Thanks for the PR.

Generally I wouldn't consider i386 worth the baggage and would go straight for `windows-amd64` only named: `inlets.exe`

What are your thoughts?

**Comment by rleungx** [comment]
Ok. BTW, do you want to separate these distributions into different targets?

**Comment by alexellis** [comment]
Hi I would like to see the following:

* only `inlets.exe` with no explicit architecture set
* Dockerfile updated (if applicable)
* .travis.yml updated (if applicable)
* Anything else updated where we create or package a binary
* README updated to say Windows support available, but experimental

Alex

**Comment by alexellis** [comment]
Hi @rleungx this is going to need a quick rebase. Please be careful not to do a merge commit.

Alex

**Comment by rleungx** [comment]
Hi, sorry for late. Does this PR still need?

**Comment by alexellis** [comment]
Hi @rleungx, this PR is still needed, thank you!

Please can you rebase your changes?

```
git remote add upstream https://github.com/alexellis/inlets
git fetch upstream
git pull upstream master --rebase

# Fix any conflicts

git add .
git commit -s
git push origin windows-binary --force
```

^ That should fix it up 👍 

Alex

**Comment by alexellis** [comment]
I just tried doing a rebase, and it was a bit tricky. You may want to raise a new PR and add your changes into master. See what's easier for you?

**Pull request closed without merging**
